### PR TITLE
Remove dhparams.pem and chain.pem check

### PR DESCRIPTION
**Pull request by seanthegeek**
These files are not needed with the new nginx config

### CODE REVIEW

**Comment by seanthegeek** [comment]
In nginx you can chain the entire cert chain in `cert.pem`

Also, [dhparams don't need to be secret](https://security.stackexchange.com/questions/94390/whats-the-purpose-of-dh-parameters) 

> It's no risk publishing them. In fact they're sent out for every key-exchange that involves some Diffie-Hellman (DH) key exchange. There are even a few such parameters standardized for example in RFC 5114.

**Comment by coolacid** [comment]
Ok, cool, so we can drop the CA chain bit (and the copy further down) but should still keep and generate the DHParam file.

**Comment by seanthegeek** [comment]
With the tlsv1.3 configuration from the earlier patch, you don't need a dhparams file.

**Comment by coolacid** [comment]
Learning!

Ok, drop the cp on line 73 (there about) and we'll pull the trigger. I'm hoping anyone that uses this supports TLS1.3, however I somehow know that some orgs aren't that quick to update. We'll play it by ear and add in the older stuff if someone notices.

**Comment by seanthegeek** [comment]
Forgot I hadn't done that yet. Done. :)

**Pull request merged**
