### PR TITLE
Make mysql data persistent

### PR DESCRIPTION
**Pull request by seanthegeek**
Fixes issue #47

### CODE REVIEW

**Comment by coolacid** [comment]
I'm debating on this. 
- It shouldn't be needed
- You can add it to your local build for docker-compose if you're design requires it
- I recommend running an external MySQL instance for prod deployments

**Comment by seanthegeek** [comment]
Why shouldn't it be needed? Should the data be persistent without it? As soon as I bring down the containers and bring them back up the databases are gone.

Even for dev instances, it's good to have persistent data.  And if someone like me is new to docker, they wouldn't expect their data to disappear,

**Comment by coolacid** [comment]
I have no problem turning mine down and back up without loosing my DB, so not sure why you are. I need to do some more testing to see what is causing that.

**Comment by coolacid** [comment]
I did some testing and found out where my mistake was. Thanks for pointing it out! 

I chose to use anonymous mount in 905d75b704c2b4184597f054866dc67a7b30f49c so that it can be deleted automagically using docker commands. Thus:

- If you do `docker-compose up` and `ctrl-c` to exit, you can delete the containers and volume mounts with `docker-compose rm -v` 

- If you do `docker-compose up -d` (which is the one I wasn't useing/testing) you can delete the volume using `docker-compose down -v` 

In ether case, just exiting the container doesn't delete the volume.

**Pull request closed without merging**
