### PR TITLE
Update dockerfile for MISP modules

### PR DESCRIPTION
**Pull request by seanthegeek**
Workaround issues reported in https://github.com/MISP/misp-modules/issues/354

- Use `touch` to add missing `misp_modules/modules/expansion/_ransomcoindb/__init__.py` that prevents the service from starting
- Install `faup` and Python bindings

### CODE REVIEW

**Comment by coolacid** [comment]
Going to leave this open for now. I want to hold on to it, but clean up the way docker builds the bits. I also want to push for https://github.com/MISP/misp-modules/pull/373 so we don't have to monkey this.

**Comment by seanthegeek** [comment]
Thanks for pushing for https://github.com/MISP/misp-modules/pull/373 it's amazing that such a simple problem has been ignored for over three months!

**Comment by coolacid** [comment]
I see this fixes two different issues, so later i'll work on getting the one bit fixed, then wait for the MISP kids to fix their side.

**Comment by coolacid** [comment]
Ok, pushed a much cleaner dockerfile, cleaning up some of my build stuff too. Also, needed to import the library into the real image. I'm going to close this PR in favour of the issue to track the upstream bug from MISP.

**Pull request closed without merging**
